# Generated by Django 4.2.8 on 2023-12-29 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('tank_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('nation', models.TextField(blank=True, null=True)),
                ('is_premium', models.IntegerField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('image_preview', models.TextField(blank=True, null=True)),
                ('image_normal', models.TextField(blank=True, null=True)),
                ('tier', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'test',
                'managed': False,
            },
        ),
    ]
