# Generated by Django 4.2.8 on 2023-12-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('externalApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='namepic',
            name='id',
        ),
        migrations.AddField(
            model_name='namepic',
            name='image_normal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='namepic',
            name='image_preview',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='namepic',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='namepic',
            name='tank_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
