# Generated by Django 4.2.8 on 2023-12-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('externalApi', '0002_remove_namepic_id_namepic_image_normal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tanks',
            fields=[
                ('tank_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('image_preview', models.CharField(blank=True, max_length=255, null=True)),
                ('image_normal', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='namePic',
        ),
    ]
