# Generated by Django 4.2.8 on 2024-03-23 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Engines',
            fields=[
                ('module_id', models.IntegerField(primary_key=True, serialize=False)),
                ('engine_power', models.SmallIntegerField(blank=True, null=True)),
                ('fire_chance', models.FloatField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'engines',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExtapiEngine',
            fields=[
                ('module_id', models.IntegerField(primary_key=True, serialize=False)),
                ('engine_power', models.IntegerField(blank=True, null=True)),
                ('fire_chance', models.FloatField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'extApi_engine',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExtapiGun',
            fields=[
                ('module_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type1', models.CharField(blank=True, max_length=255, null=True)),
                ('pen1', models.IntegerField(blank=True, null=True)),
                ('dmg1', models.IntegerField(blank=True, null=True)),
                ('type2', models.CharField(blank=True, max_length=255, null=True)),
                ('pen2', models.IntegerField(blank=True, null=True)),
                ('dmg2', models.IntegerField(blank=True, null=True)),
                ('type3', models.CharField(blank=True, max_length=255, null=True)),
                ('pen3', models.IntegerField(blank=True, null=True)),
                ('dmg3', models.IntegerField(blank=True, null=True)),
                ('dispersion', models.FloatField(blank=True, null=True)),
                ('aim_time', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'extApi_gun',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExtapiSuspension',
            fields=[
                ('module_id', models.IntegerField(primary_key=True, serialize=False)),
                ('traverse_speed', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'extApi_suspension',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExtapiTank',
            fields=[
                ('tank_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('image_preview', models.CharField(blank=True, max_length=255, null=True)),
                ('image_normal', models.CharField(blank=True, max_length=255, null=True)),
                ('is_premium', models.IntegerField(blank=True, null=True)),
                ('nation', models.CharField(blank=True, max_length=255, null=True)),
                ('tier', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('caliber', models.IntegerField(blank=True, null=True)),
                ('clip_capacity', models.IntegerField(blank=True, null=True)),
                ('clip_reload_time', models.FloatField(blank=True, null=True)),
                ('fire_rate', models.FloatField(blank=True, null=True)),
                ('front', models.IntegerField(blank=True, null=True)),
                ('gun_traverse_speed', models.FloatField(blank=True, null=True)),
                ('hp', models.IntegerField(blank=True, null=True)),
                ('hull_hp', models.IntegerField(blank=True, null=True)),
                ('move_down_arc', models.IntegerField(blank=True, null=True)),
                ('move_up_arc', models.IntegerField(blank=True, null=True)),
                ('rear', models.IntegerField(blank=True, null=True)),
                ('reload_time', models.FloatField(blank=True, null=True)),
                ('sides', models.IntegerField(blank=True, null=True)),
                ('speed_backward', models.IntegerField(blank=True, null=True)),
                ('speed_forward', models.IntegerField(blank=True, null=True)),
                ('turret_traverse_speed', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'extApi_tank',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExtapiTankEngines',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'extApi_tank_engines',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExtapiTankGuns',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'extApi_tank_guns',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExtapiTankSuspensions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'extApi_tank_suspensions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExtapiTankTurrets',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'extApi_tank_turrets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExtapiTurret',
            fields=[
                ('module_id', models.IntegerField(primary_key=True, serialize=False)),
                ('view_range', models.IntegerField(blank=True, null=True)),
                ('front', models.IntegerField(blank=True, null=True)),
                ('sides', models.IntegerField(blank=True, null=True)),
                ('rear', models.IntegerField(blank=True, null=True)),
                ('hp', models.IntegerField(blank=True, null=True)),
                ('traverse_right_arc', models.IntegerField(blank=True, null=True)),
                ('traverse_left_arc', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'extApi_turret',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Guns',
            fields=[
                ('module_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type1', models.CharField(blank=True, max_length=20, null=True)),
                ('pen1', models.SmallIntegerField(blank=True, null=True)),
                ('dmg1', models.SmallIntegerField(blank=True, null=True)),
                ('type2', models.CharField(blank=True, max_length=20, null=True)),
                ('pen2', models.SmallIntegerField(blank=True, null=True)),
                ('dmg2', models.SmallIntegerField(blank=True, null=True)),
                ('type3', models.CharField(blank=True, max_length=20, null=True)),
                ('pen3', models.SmallIntegerField(blank=True, null=True)),
                ('dmg3', models.SmallIntegerField(blank=True, null=True)),
                ('dispersion', models.FloatField(blank=True, null=True)),
                ('aim_time', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'guns',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Suspensions',
            fields=[
                ('module_id', models.IntegerField(primary_key=True, serialize=False)),
                ('traverse_speed', models.SmallIntegerField(blank=True, null=True)),
                ('weight', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'suspensions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TankGuns',
            fields=[
                ('pair_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tankguns',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tanks',
            fields=[
                ('tank_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('image_preview', models.CharField(blank=True, max_length=200, null=True)),
                ('image_normal', models.CharField(blank=True, max_length=200, null=True)),
                ('nation', models.CharField(blank=True, max_length=20, null=True)),
                ('is_premium', models.CharField(blank=True, max_length=1, null=True)),
                ('tier', models.SmallIntegerField(blank=True, null=True)),
                ('tank_type', models.CharField(blank=True, max_length=20, null=True)),
                ('front', models.SmallIntegerField(blank=True, null=True)),
                ('sides', models.SmallIntegerField(blank=True, null=True)),
                ('rear', models.SmallIntegerField(blank=True, null=True)),
                ('speed_forward', models.SmallIntegerField(blank=True, null=True)),
                ('speed_backward', models.SmallIntegerField(blank=True, null=True)),
                ('hp', models.SmallIntegerField(blank=True, null=True)),
                ('move_down_arc', models.SmallIntegerField(blank=True, null=True)),
                ('move_up_arc', models.SmallIntegerField(blank=True, null=True)),
                ('caliber', models.SmallIntegerField(blank=True, null=True)),
                ('fire_rate', models.FloatField(blank=True, null=True)),
                ('reload_time', models.FloatField(blank=True, null=True)),
                ('clip_capacity', models.SmallIntegerField(blank=True, null=True)),
                ('clip_reload_time', models.FloatField(blank=True, null=True)),
                ('gun_traverse_speed', models.FloatField(blank=True, null=True)),
                ('turret_traverse_speed', models.SmallIntegerField(blank=True, null=True)),
                ('hull_hp', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tanks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Turrets',
            fields=[
                ('module_id', models.IntegerField(primary_key=True, serialize=False)),
                ('view_range', models.SmallIntegerField(blank=True, null=True)),
                ('front', models.SmallIntegerField(blank=True, null=True)),
                ('sides', models.SmallIntegerField(blank=True, null=True)),
                ('rear', models.SmallIntegerField(blank=True, null=True)),
                ('hp', models.SmallIntegerField(blank=True, null=True)),
                ('traverse_right_arc', models.SmallIntegerField(blank=True, null=True)),
                ('traverse_left_arc', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'turrets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TankEngines',
            fields=[
                ('tank', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.tanks')),
            ],
            options={
                'db_table': 'tank_engines',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TankSuspensions',
            fields=[
                ('tank', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.tanks')),
            ],
            options={
                'db_table': 'tank_suspensions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TankTurrets',
            fields=[
                ('tank', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.tanks')),
            ],
            options={
                'db_table': 'tank_turrets',
                'managed': False,
            },
        ),
    ]
