# Generated by Django 4.2.8 on 2023-12-30 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tanks',
            fields=[
                ('tank_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('image_preview', models.CharField(blank=True, max_length=255, null=True)),
                ('image_normal', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
