# Generated by Django 4.2.8 on 2023-12-30 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanks',
            name='is_premium',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tanks',
            name='nation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tanks',
            name='tier',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tanks',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
