# Generated by Django 4.2.8 on 2024-01-03 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extApi', '0002_tanks_is_premium_tanks_nation_tanks_tier_tanks_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tanks',
            options={'verbose_name_plural': 'Tanks'},
        ),
    ]
