# Generated by Django 4.2.8 on 2024-01-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extApi', '0004_rename_tanks_tank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('module_id', models.IntegerField(primary_key=True, serialize=False)),
                ('engine_power', models.IntegerField(blank=True, null=True)),
                ('fire_chance', models.FloatField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gun',
            fields=[
                ('module_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type1', models.CharField(blank=True, max_length=255, null=True)),
                ('pen1', models.IntegerField(blank=True, null=True)),
                ('dmg1', models.IntegerField(blank=True, null=True)),
                ('type2', models.CharField(blank=True, max_length=255, null=True)),
                ('pen2', models.IntegerField(blank=True, null=True)),
                ('dmg2', models.IntegerField(blank=True, null=True)),
                ('type3', models.CharField(blank=True, max_length=255, null=True)),
                ('pen3', models.IntegerField(blank=True, null=True)),
                ('dmg3', models.IntegerField(blank=True, null=True)),
                ('dispersion', models.FloatField(blank=True, null=True)),
                ('aim_time', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suspension',
            fields=[
                ('module_id', models.IntegerField(primary_key=True, serialize=False)),
                ('traverse_speed', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Turret',
            fields=[
                ('module_id', models.IntegerField(primary_key=True, serialize=False)),
                ('view_range', models.IntegerField(blank=True, null=True)),
                ('front', models.IntegerField(blank=True, null=True)),
                ('sides', models.IntegerField(blank=True, null=True)),
                ('rear', models.IntegerField(blank=True, null=True)),
                ('hp', models.IntegerField(blank=True, null=True)),
                ('traverse_right_arc', models.IntegerField(blank=True, null=True)),
                ('traverse_left_arc', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='tank',
            options={},
        ),
        migrations.AddField(
            model_name='tank',
            name='caliber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tank',
            name='clip_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tank',
            name='clip_reload_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tank',
            name='fire_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tank',
            name='front',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tank',
            name='gun_traverse_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tank',
            name='hp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tank',
            name='hull_hp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tank',
            name='move_down_arc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tank',
            name='move_up_arc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tank',
            name='rear',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tank',
            name='reload_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tank',
            name='sides',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tank',
            name='speed_backward',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tank',
            name='speed_forward',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tank',
            name='turret_traverse_speed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tank',
            name='engines',
            field=models.ManyToManyField(to='extApi.engine'),
        ),
        migrations.AddField(
            model_name='tank',
            name='guns',
            field=models.ManyToManyField(to='extApi.gun'),
        ),
        migrations.AddField(
            model_name='tank',
            name='suspensions',
            field=models.ManyToManyField(to='extApi.suspension'),
        ),
        migrations.AddField(
            model_name='tank',
            name='turrets',
            field=models.ManyToManyField(to='extApi.turret'),
        ),
    ]
