# Generated by Django 4.2.8 on 2024-01-03 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('tank_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('image_preview', models.CharField(blank=True, max_length=255, null=True)),
                ('image_normal', models.CharField(blank=True, max_length=255, null=True)),
                ('nation', models.CharField(blank=True, max_length=255, null=True)),
                ('is_premium', models.IntegerField(blank=True, null=True)),
                ('tier', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Results',
            },
        ),
    ]
